### ISSUE TITLE
jar should not include logback.xml

### ISSUE THREAD

**Issue by cbeeton** [jamesmorgan/ReloadablePropertiesAnnotation#16]
jars should not include logback.xml as that means that applications that use logback will encounter "Resource [logback.xml] occurs multiple times on the classpath." warnings, and since this jar configures a console logger for stdout, my application gets noise on stdout that I cannot turn off.

**Comment by jamesmorgan** [comment]
See https://github.com/jamesmorgan/ReloadablePropertiesAnnotation/pull/17
