### ISSUE TITLE
Changes in property file asks for server restart

### ISSUE THREAD

**Issue by Tameem510** [jamesmorgan/ReloadablePropertiesAnnotation#20]
I downloaded the sample project and added to my server. Tried to change the values in property file and saved it. The tomcat server is asking for a restart. This project is actually a solution for dynamic property changes without server restart rite?

**Comment by jamesmorgan** [comment]
It is a solution for dynamic properties. Do you have auto reload of all files enabled within tomcat? Closing issue as this is not really an issue but a question. 

The project is not maintained to any length and is really a demonstration of how to do it and not a library to use it.
